In [2]:
import numpy as np

# 一、numpy内置函数

## 1、numpy弧度制与角度值的转化

In [22]:
# 角度转弧度
print(np.deg2rad(45))
print(45*np.pi/180)

0.7853981633974483
0.7853981633974483


In [24]:
# 弧度转角度
print(np.rad2deg(np.pi/2))
print(np.pi/2*180/np.pi)

90.0
90.0


## 2、三角函数

In [8]:
a = np.array([0,30,45,60,90])
print ('不同角度的正弦值：')
# 通过乘 pi/180 转化为弧度  
print (np.sin(a*np.pi/180))
print ('数组中角度的余弦值：')
print (np.cos(a*np.pi/180))
print ('数组中角度的正切值：')
print (np.tan(a*np.pi/180))

不同角度的正弦值：
[0.         0.5        0.70710678 0.8660254  1.        ]
数组中角度的余弦值：
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
数组中角度的正切值：
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


In [15]:
a = np.array([0,30,45,60,90])  
print ('含有正弦值的数组：')
sin = np.sin(a*np.pi/180)
print(sin)
print ('计算角度的反正弦，返回值以弧度为单位：')
inv = np.arcsin(sin)  
print (inv)
print ('通过转化为角度制来检查结果：')
print (np.degrees(inv))
print ('arccos 和 arctan 函数行为类似：')
cos = np.cos(a*np.pi/180)  
print (cos)
print ('反余弦：')
inv = np.arccos(cos)  
print (inv)
print ('角度制单位：')
print (np.degrees(inv))
print ('tan 函数：')
tan = np.tan(a*np.pi/180)  
print (tan)
print ('反正切：')
inv = np.arctan(tan)  
print (inv)
print ('角度制单位：')
print (np.degrees(inv))

含有正弦值的数组：
[0.         0.5        0.70710678 0.8660254  1.        ]
计算角度的反正弦，返回值以弧度为单位：
[0.         0.52359878 0.78539816 1.04719755 1.57079633]
通过转化为角度制来检查结果：
[ 0. 30. 45. 60. 90.]
arccos 和 arctan 函数行为类似：
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
反余弦：
[0.         0.52359878 0.78539816 1.04719755 1.57079633]
角度制单位：
[ 0. 30. 45. 60. 90.]
tan 函数：
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]
反正切：
[0.         0.52359878 0.78539816 1.04719755 1.57079633]
角度制单位：
[ 0. 30. 45. 60. 90.]


## 3、数据统计

In [ ]:
arr = np.array([[33, 55], [11, 66], [22, 99]])
# print(arr)
# 最大值
# print(np.max(arr))
# 最小值
# print(np.min(arr))
# 某一轴上的最大值
print(np.max(arr, 0))
# 某一轴上的最小值
print(np.min(arr, 0))
# 平均值
print(np.mean(arr))
# 某一行、一列的平均值
print(np.mean(arr, axis=1))
# 最大值索引
print(np.argmax(arr))
print(np.argmax(arr, axis=1))
# 最小值索引
print(np.argmin(arr))
print(np.argmin(arr, axis=1))
# 极差
print(np.ptp(arr))
print(np.ptp(arr, axis=1))
# 方差
print(np.var(arr))
# 标准差
print(np.std(arr))
# 中位数
print(np.median(arr))

## 4、数组排序

In [ ]:
a = np.array([[3, 7, 1],[9, 1, 5]])
# 逐行排序
np.sort(a)

# axis = 0：按列排序
# axis = 1：按行排序
np.sort(a, axis =  1)

In [ ]:
# 在 sort 函数中排序字段 
dt = np.dtype([('name',  'S10'),('age',  int)]) 
a = np.array([("raju",21),("anil",25),("ravi",  17),  ("amar",27)], dtype = dt)  
print ('我们的数组是：')
print (a)
print ('\n')
print ('按 name 排序：')
print (np.sort(a, order =  'name'))

## 5、返回数组索引

### 5.1、`numpy.argsort()`

> 返回的是数组值从小到大的索引值

In [3]:
z = np.array([1, 3, 2, 4, 0])
f = np.argsort(z)
z[f]

array([0, 1, 2, 3, 4])

### 5.2、`enumerate()`函数

    enumerate() 是 Python 的一个内置函数，它用于将一个可遍历的数据对象（如列表、元组或字符串）组合成一个索引序列，同时列出数据和数据下标。这个函数一般用在 for 循环当中。

In [4]:
s = np.arange(0, 1, 0.01)
# 参数：
# - sequence: 一个序列、迭代器或其他支持迭代对
# - start: 下标起始位置。默认为0。
for i, v in enumerate(s):  
    print(i, v)

0 0.0
1 0.01
2 0.02
3 0.03
4 0.04
5 0.05
6 0.06
7 0.07
8 0.08
9 0.09
10 0.1
11 0.11
12 0.12
13 0.13
14 0.14
15 0.15
16 0.16
17 0.17
18 0.18
19 0.19
20 0.2
21 0.21
22 0.22
23 0.23
24 0.24
25 0.25
26 0.26
27 0.27
28 0.28
29 0.29
30 0.3
31 0.31
32 0.32
33 0.33
34 0.34
35 0.35000000000000003
36 0.36
37 0.37
38 0.38
39 0.39
40 0.4
41 0.41000000000000003
42 0.42
43 0.43
44 0.44
45 0.45
46 0.46
47 0.47000000000000003
48 0.48
49 0.49
50 0.5
51 0.51
52 0.52
53 0.53
54 0.54
55 0.55
56 0.56
57 0.5700000000000001
58 0.58
59 0.59
60 0.6
61 0.61
62 0.62
63 0.63
64 0.64
65 0.65
66 0.66
67 0.67
68 0.68
69 0.6900000000000001
70 0.7000000000000001
71 0.71
72 0.72
73 0.73
74 0.74
75 0.75
76 0.76
77 0.77
78 0.78
79 0.79
80 0.8
81 0.81
82 0.8200000000000001
83 0.8300000000000001
84 0.84
85 0.85
86 0.86
87 0.87
88 0.88
89 0.89
90 0.9
91 0.91
92 0.92
93 0.93
94 0.9400000000000001
95 0.9500000000000001
96 0.96
97 0.97
98 0.98
99 0.99


# 二、矩阵运算

In [5]:
# 矩阵转置
a = np.array([[1, 2, 3], [4, 5, 6]])
a = np.transpose(a)
a

array([[1, 4],
       [2, 5],
       [3, 6]])

## 1、矩阵和数的运算

In [ ]:
arr = np.arange(12).reshape(3, 4)
arr

# 加减乘除
# print(arr + 3, end='\n\n')
# print(arr - 1, end='\n\n')
# print(arr * 2, end='\n\n')
# print(arr / 3, end='\n\n')

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## 2、矩阵之间的运算

In [43]:
# 行列相等
""" a = np.linspace(1, 12, 12).reshape(3, 4)
b = np.linspace(13, 24, 12).reshape(3, 4)
a + b
a - b
a * b """

# 相同行数【并且只有一列才管用】
a = np.arange(12).reshape(3, 4)
b = np.arange(3).reshape(3, 1)
a + b

array([[ 0,  1,  2,  3],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13]])

## 3、numpy统计指标

[33 99]
[11 55]
47.666666666666664
[44.  38.5 60.5]
5
[1 1 1]
2
[0 0 0]
88
[22 55 77]
873.8888888888888
29.561611743761347
44.0


## 4、构造特殊矩阵

### 4.1、构造全0矩阵

In [6]:
# 这样写就是 1*10，一行十列
a = np.zeros(10)
print(a)
print(a.shape, type(a))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
(10,) <class 'numpy.ndarray'>


In [7]:
# 可以在第一个参数上规定矩阵的形状
b = np.zeros((10, 10))
print(b)
print(b.shape, type(b))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
(10, 10) <class 'numpy.ndarray'>


### 4.2、构造全1矩阵

In [ ]:
c1 = np.ones(10)
print(c1)
print(c1.shape, type(c1))

In [ ]:
c2 = np.ones((10, 10))
print(c2)
print(c2.shape, type(c2))

## 5、矩阵特征值计算

### 5.1、矩阵对角化

In [ ]:
x = np.arange(0, 10, 1)
y = np.diag(x, 1)
print(y)

### 5.2、numpy求解特征值c

In [6]:
a = np.diag((1,2,3)) # 一个对角矩阵
w, v = np.linalg.eig(a)
print(w)

[1. 2. 3.]


### 5.3、scipy求解特征值

In [ ]:
a = np.array([[1, 2], [3, 1+1.j]])
print('a:', a, '\n')
sigma_y = np.array([[0, -1.j], [1.j, 0]])
print('sigma_y:', sigma_y)
# 元素和平方之后再开方
la.norm(a) ** 2

la.norm(a-a)
# 厄米共轭
np.matrix(sigma_y).H
# 建议用下面的方式
sigma_y.transpose().conj()

In [ ]:
# 判断矩阵是否是厄米矩阵
def assert_hermitian(hami):
    assert la.norm(hami - hami.transpose().conj()) < 1e-6, f'hami is hermitian'
    return True
# assert_hermitian(a)
assert_hermitian(sigma_y)

In [ ]:
# 求矩阵本征值
la.eigh(a)

# 三、numpy的执行速度

## 1、比较numpy和python math库运行速度

In [4]:
x = np.arange(0, 1000000, 0.01)
t_m1 = time.process_time()
for i, t in enumerate(x):
    x[i] = math.pow(math.sin(t), 2)
t_m2 = time.process_time()
print('math：', t_m2 - t_m1)

math： 20.535021


In [5]:
y = np.arange(0, 1000000, 0.01)
t_n1 = time.process_time()
y = np.power(np.sin(y), 2)
t_n2 =time.process_time()

print('numpy：', t_n2 - t_n1)

numpy： 1.7348389999999974
