In [34]:
import numpy as np
import json
import time
import math

# 一、创建numpy数组

## 1、一维数组

In [5]:
arr1 = np.array([1, 2, 3, 4, 5])
print ("arr1：", arr1, type(arr1))
arr2 = np.array(range(1, 6))
print ("arr2：", arr2, type(arr2))
# 直接arange出来也是数组
arr3 = np.arange(1, 10)
print ("arr3：", arr3, type(arr3))

arr1： [1 2 3 4 5] <class 'numpy.ndarray'>
arr2： [1 2 3 4 5] <class 'numpy.ndarray'>
arr3： [1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>


## 2、创建二维数组

In [21]:
arr = np.array([[1, 2], [3, 4], [5, 6]])
print(arr)
# 取值，等价于arr[0, 1]
print(arr[0][1])
print(arr[2])

[[1 2]
 [3 4]
 [5 6]]
2
[5 6]


## 3、ndarray 常用方法

In [13]:
arr = np.array([[1, 2], [3, 4], [5, 6]])

# 元素类型
print("arr.dtype:", arr.dtype)
# 形状【就是矩阵的维度】
print('arr.shape:', arr.shape)
# 元素个数
print("arr.size:", arr.size)
# 维度
print('arr.ndim:', arr.ndim)
# 每个元素大小（字节）
print('arr.itemsize:', arr.itemsize)

arr.dtype: int64
arr.shape: (3, 2)
arr.size: 6
arr.ndim: 2
arr.itemsize: 8


In [14]:
arr = np.array([[1, 2], [3, 4], [5, 6]])

# 重新定义维度
print('arr.reshape:', arr.reshape(2, 3))

arr.reshape: [[1 2 3]
 [4 5 6]]


In [16]:
# 矩阵的实部虚部
arr = np.array([1+2j, 4j])
print('arr.ndim:', arr.ndim)

# arr = np.array([[1, 2], [3, 4], [5, 6]])
print('arr.real:', arr.real)
print('arr.imag:', arr.imag)
print('arr.T:', arr.T)

arr.ndim: 1
arr.real: [1. 0.]
arr.imag: [2. 4.]
arr.T: [1.+2.j 0.+4.j]


In [18]:
# arange() 方法
myArr01 = np.arange(30)
# 变成 2 维数组
myArr01.reshape(3, 10)
# 变成 3 维数组
myArr01.reshape(2, 3, 5)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [17]:
# 多维数组取值
myArr02 = np.arange(12).reshape(3, 4)
myArr02[:1]

array([[0, 1, 2, 3]])

## 4、视图与副本

In [22]:
# 创建视图
a = np.arange(12).reshape(3, 4)
b = a.view()

a[0, 0] = 100
print(id(a), id(b))
b.shape = 4, 3
a.shape, b.shape

4396676848 4396676272


((3, 4), (4, 3))

In [27]:
# 创建副本【任然是 shallow copy】
c = a.copy()
a[0, 0] = 999
c is a

False

In [30]:
# test np.copy()
""" arr = [[1, 2], [3, 4, [4, 1]]]
arrCopy = arr.copy()
# arr[1][2][0] = '==='
arrCopy """

# 测试 json.dunps() 果然是深拷贝
arr = [[1, 2], [3, 4, [4, 1]]]
arrCopy = json.loads(json.dumps(repr(arr)))
arr[1][2][0] = '==='
arrCopy

'[[1, 2], [3, 4, [4, 1]]]'

# 二、numpy内建函数

## 1、numpy弧度制与角度值的转化

In [ ]:
# 角度转弧度
print(np.deg2rad(45))
print(45*np.pi/180)

In [ ]:
# 弧度转角度
print(np.rad2deg(np.pi/2))
print(np.pi/2*180/np.pi)

## 2、三角函数

In [ ]:
a = np.array([0,30,45,60,90])
print ('不同角度的正弦值：')
# 通过乘 pi/180 转化为弧度  
print (np.sin(a*np.pi/180))
print ('数组中角度的余弦值：')
print (np.cos(a*np.pi/180))
print ('数组中角度的正切值：')
print (np.tan(a*np.pi/180))

In [ ]:
a = np.array([0,30,45,60,90])  
print ('含有正弦值的数组：')
sin = np.sin(a*np.pi/180)
print(sin)
print ('计算角度的反正弦，返回值以弧度为单位：')
inv = np.arcsin(sin)  
print (inv)
print ('通过转化为角度制来检查结果：')
print (np.degrees(inv))
print ('arccos 和 arctan 函数行为类似：')
cos = np.cos(a*np.pi/180)  
print (cos)
print ('反余弦：')
inv = np.arccos(cos)  
print (inv)
print ('角度制单位：')
print (np.degrees(inv))
print ('tan 函数：')
tan = np.tan(a*np.pi/180)  
print (tan)
print ('反正切：')
inv = np.arctan(tan)  
print (inv)
print ('角度制单位：')
print (np.degrees(inv))

## 3、数据统计

In [ ]:
arr = np.array([[33, 55], [11, 66], [22, 99]])
# print(arr)
# 最大值
# print(np.max(arr))
# 最小值
# print(np.min(arr))
# 某一轴上的最大值
print(np.max(arr, 0))
# 某一轴上的最小值
print(np.min(arr, 0))
# 平均值
print(np.mean(arr))
# 某一行、一列的平均值
print(np.mean(arr, axis=1))
# 最大值索引
print(np.argmax(arr))
print(np.argmax(arr, axis=1))
# 最小值索引
print(np.argmin(arr))
print(np.argmin(arr, axis=1))
# 极差
print(np.ptp(arr))
print(np.ptp(arr, axis=1))
# 方差
print(np.var(arr))
# 标准差
print(np.std(arr))
# 中位数
print(np.median(arr))

## 4、数组排序

In [ ]:
a = np.array([[3, 7, 1],[9, 1, 5]])
# 逐行排序
np.sort(a)

# axis = 0：按列排序
# axis = 1：按行排序
np.sort(a, axis =  1)

In [ ]:
# 在 sort 函数中排序字段 
dt = np.dtype([('name',  'S10'),('age',  int)]) 
a = np.array([("raju",21),("anil",25),("ravi",  17),  ("amar",27)], dtype = dt)  
print ('我们的数组是：')
print (a)
print ('\n')
print ('按 name 排序：')
print (np.sort(a, order =  'name'))

## 5、返回数组索引

### 5.1、`numpy.argsort()`

> 返回的是数组值从小到大的索引值

In [ ]:
z = np.array([1, 3, 2, 4, 0])
f = np.argsort(z)
z[f]

### 5.2、`enumerate()`函数

    enumerate() 是 Python 的一个内置函数，它用于将一个可遍历的数据对象（如列表、元组或字符串）组合成一个索引序列，同时列出数据和数据下标。这个函数一般用在 for 循环当中。

In [ ]:
s = np.arange(0, 1, 0.01)
# 参数：
# - sequence: 一个序列、迭代器或其他支持迭代对
# - start: 下标起始位置。默认为0。
for i, v in enumerate(s):  
    print(i, v)

## 6、数组类型转换

## 6.1、字符数组转化为数值数组

In [7]:
# 将字符数组转化为数值数组
a = np.array(['1', '2', 3])
b = a.astype(np.float64)
b

array([1., 2., 3.])

# 二、矩阵运算

In [ ]:
# 矩阵转置
a = np.array([[1, 2, 3], [4, 5, 6]])
a = np.transpose(a)
a

## 1、矩阵和数的运算

In [ ]:
arr = np.arange(12).reshape(3, 4)
arr

# 加减乘除
# print(arr + 3, end='\n\n')
# print(arr - 1, end='\n\n')
# print(arr * 2, end='\n\n')
# print(arr / 3, end='\n\n')

## 2、矩阵之间的运算

In [ ]:
# 行列相等
""" a = np.linspace(1, 12, 12).reshape(3, 4)
b = np.linspace(13, 24, 12).reshape(3, 4)
a + b
a - b
a * b """

# 相同行数【并且只有一列才管用】
a = np.arange(12).reshape(3, 4)
b = np.arange(3).reshape(3, 1)
a + b

## 3、numpy统计指标

## 4、构造特殊矩阵

### 4.1、构造全0矩阵

In [ ]:
# 这样写就是 1*10，一行十列
a = np.zeros(10)
print(a)
print(a.shape, type(a))

In [ ]:
# 可以在第一个参数上规定矩阵的形状
b = np.zeros((10, 10))
print(b)
print(b.shape, type(b))

### 4.2、构造全1矩阵

In [ ]:
c1 = np.ones(10)
print(c1)
print(c1.shape, type(c1))

In [ ]:
c2 = np.ones((10, 10))
print(c2)
print(c2.shape, type(c2))

## 5、矩阵特征值计算

### 5.1、矩阵对角化

In [ ]:
x = np.arange(0, 10, 1)
y = np.diag(x, 1)
print(y)

### 5.2、numpy求解特征值c

In [ ]:
a = np.diag((1,2,3)) # 一个对角矩阵
w, v = np.linalg.eig(a)
print(w)

### 5.3、scipy求解特征值

In [ ]:
a = np.array([[1, 2], [3, 1+1.j]])
print('a:', a, '\n')
sigma_y = np.array([[0, -1.j], [1.j, 0]])
print('sigma_y:', sigma_y)
# 元素和平方之后再开方
la.norm(a) ** 2

la.norm(a-a)
# 厄米共轭
np.matrix(sigma_y).H
# 建议用下面的方式
sigma_y.transpose().conj()

In [ ]:
# 判断矩阵是否是厄米矩阵
def assert_hermitian(hami):
    assert la.norm(hami - hami.transpose().conj()) < 1e-6, f'hami is hermitian'
    return True
# assert_hermitian(a)
assert_hermitian(sigma_y)

In [ ]:
# 求矩阵本征值
la.eigh(a)

# 三、numpy的执行速度

## 1、比较numpy和python math库运行速度

In [35]:
x = np.arange(0, 1000000, 0.01)
t_m1 = time.process_time()
for i, t in enumerate(x):
    x[i] = math.pow(math.sin(t), 2)
t_m2 = time.process_time()
print('math：', t_m2 - t_m1)

math： 20.510344


In [36]:
y = np.arange(0, 1000000, 0.01)
t_n1 = time.process_time()
y = np.power(np.sin(y), 2)
t_n2 =time.process_time()

print('numpy：', t_n2 - t_n1)

numpy： 1.6435069999999996
