In [1]:
import numpy as np

# numpy弧度制与角度值的转化

In [22]:
# 角度转弧度
print(np.deg2rad(45))
print(45*np.pi/180)

0.7853981633974483
0.7853981633974483


In [24]:
# 弧度转角度
print(np.rad2deg(np.pi/2))
print(np.pi/2*180/np.pi)

90.0
90.0


# 三角函数

In [8]:
a = np.array([0,30,45,60,90])
print ('不同角度的正弦值：')
# 通过乘 pi/180 转化为弧度  
print (np.sin(a*np.pi/180))
print ('数组中角度的余弦值：')
print (np.cos(a*np.pi/180))
print ('数组中角度的正切值：')
print (np.tan(a*np.pi/180))

不同角度的正弦值：
[0.         0.5        0.70710678 0.8660254  1.        ]
数组中角度的余弦值：
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
数组中角度的正切值：
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


# 反三角函数

In [15]:
a = np.array([0,30,45,60,90])  
print ('含有正弦值的数组：')
sin = np.sin(a*np.pi/180)
print(sin)
print ('计算角度的反正弦，返回值以弧度为单位：')
inv = np.arcsin(sin)  
print (inv)
print ('通过转化为角度制来检查结果：')
print (np.degrees(inv))
print ('arccos 和 arctan 函数行为类似：')
cos = np.cos(a*np.pi/180)  
print (cos)
print ('反余弦：')
inv = np.arccos(cos)  
print (inv)
print ('角度制单位：')
print (np.degrees(inv))
print ('tan 函数：')
tan = np.tan(a*np.pi/180)  
print (tan)
print ('反正切：')
inv = np.arctan(tan)  
print (inv)
print ('角度制单位：')
print (np.degrees(inv))

含有正弦值的数组：
[0.         0.5        0.70710678 0.8660254  1.        ]
计算角度的反正弦，返回值以弧度为单位：
[0.         0.52359878 0.78539816 1.04719755 1.57079633]
通过转化为角度制来检查结果：
[ 0. 30. 45. 60. 90.]
arccos 和 arctan 函数行为类似：
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
反余弦：
[0.         0.52359878 0.78539816 1.04719755 1.57079633]
角度制单位：
[ 0. 30. 45. 60. 90.]
tan 函数：
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]
反正切：
[0.         0.52359878 0.78539816 1.04719755 1.57079633]
角度制单位：
[ 0. 30. 45. 60. 90.]


# ndarray

In [7]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a = np.transpose(a)
a

array([[1, 4],
       [2, 5],
       [3, 6]])