## 1、矩阵和数的运算

In [16]:
import numpy as np

arr = np.arange(12).reshape(3, 4)
arr

# 加减乘除
# print(arr + 3, end='\n\n')
# print(arr - 1, end='\n\n')
# print(arr * 2, end='\n\n')
# print(arr / 3, end='\n\n')



array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## 2、矩阵之间的运算

In [43]:
# 行列相等
""" a = np.linspace(1, 12, 12).reshape(3, 4)
b = np.linspace(13, 24, 12).reshape(3, 4)
a + b
a - b
a * b """

# 相同行数【并且只有一列才管用】
a = np.arange(12).reshape(3, 4)
b = np.arange(3).reshape(3, 1)
a + b

array([[ 0,  1,  2,  3],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13]])

## 3、【最大值等等一些运算】

In [47]:
import numpy as np

arr = np.array([[33, 55], [11, 66], [22, 99]])
# print(arr)
# 最大值
# print(np.max(arr))
# 最小值
# print(np.min(arr))
# 某一轴上的最大值
print(np.max(arr, 0))
# 某一轴上的最小值
print(np.min(arr, 0))
# 平均值
print(np.mean(arr))
# 某一行、一列的平均值
print(np.mean(arr, axis=1))
# 最大值索引
print(np.argmax(arr))
print(np.argmax(arr, axis=1))
# 最小值索引
print(np.argmin(arr))
print(np.argmin(arr, axis=1))
# 极差
print(np.ptp(arr))
print(np.ptp(arr, axis=1))
# 方差
print(np.var(arr))
# 标准差
print(np.std(arr))
# 中位数
print(np.median(arr))


[33 99]
[11 55]
47.666666666666664
[44.  38.5 60.5]
5
[1 1 1]
2
[0 0 0]
88
[22 55 77]
873.8888888888888
29.561611743761347
44.0


In [48]:
# 去重
arr = [2, 1, 5, 2, 1]
np.unique(arr)

array([1, 2, 5])